#!/usr/bin/env python3
"""Serve the site and drive the browser smoke suites in headless Chrome.

There is no test runner and no build step in this project, and adding either would mean
adding a toolchain the deployed site does not have. So this is stdlib only, the same
constraint scripts/fetch_pvgis.py works under: it starts an http.server on the repo root,
loads each suite page in headless Chrome, reads the verdict back out of the dumped DOM,
and exits non-zero if anything failed.

Each suite is a plain HTML page that writes its results into <pre id="out"> and ends with
either "ALL PASS (n)" or "n FAILURES". A suite that produces neither is treated as a
failure: under a virtual time budget that means it hung rather than that it passed.

Usage:
    python _tests/run.py                 # all suites
    python _tests/run.py engine wizard   # just these
    python _tests/run.py --list
    python _tests/run.py --keep          # leave the generated fixture in place
"""

import argparse
import html
import http.server
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import threading
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TESTS = REPO / "_tests"

# Order matters only for reading the output: cheapest and most fundamental first, so a
# broken calc engine reports before the eight UI suites built on top of it repeat the news.
SUITES = [
    ("engine", "suite-engine.html", 90),
    ("wizard", "suite-wizard.html", 90),
    ("compare", "suite-compare.html", 90),
    ("i18n", "suite-i18n.html", 120),
    ("methodology", "suite-methodology.html", 90),
    ("bounds", "suite-bounds.html", 90),
    ("mobile", "suite-mobile.html", 90),
    ("a11y", "suite-a11y.html", 90),
]

# The data-error suite needs a page whose cities.json fetch fails and whose everything else
# succeeds. Keeping a committed copy of index.html for that would rot the moment index.html
# changed, so it is generated from the real page at run time instead. It lands at the repo
# root rather than in _tests/ so that every relative path inside it still resolves.
FIXTURE = REPO / "_dataerror.html"

FIXTURE_SHIM = """  <script>
    // Generated by _tests/run.py from index.html — do not edit, do not commit.
    // Fails the site data only. The catalogue still loads, so this also proves the panel is
    // shown in the reader's language rather than as a raw key.
    (function () {
      const real = window.fetch;
      window.fetch = function (url, opts) {
        if (String(url).indexOf("cities.json") >= 0) {
          return Promise.reject(new Error("simulated network failure"));
        }
        return real.call(window, url, opts);
      };
    })();
  </script>
</head>"""


def find_chrome():
    """Locate a Chrome/Chromium binary. CI runners and the three desktop platforms differ."""
    env = os.environ.get("CHROME")
    if env:
        return env

    names = [
        "google-chrome",
        "google-chrome-stable",
        "chromium",
        "chromium-browser",
        "chrome",
    ]
    for name in names:
        found = shutil.which(name)
        if found:
            return found

    candidates = [
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    ]
    for path in candidates:
        if Path(path).exists():
            return path

    sys.exit(
        "Could not find Chrome. Install it, put it on PATH, or set the CHROME environment "
        "variable to the binary."
    )


def free_port():
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


class QuietHandler(http.server.SimpleHTTPRequestHandler):
    """SimpleHTTPRequestHandler logs every request to stderr; a suite makes hundreds."""

    def log_message(self, *args):
        pass


def serve(port):
    handler = lambda *a, **kw: QuietHandler(*a, directory=str(REPO), **kw)
    # Threading is not optional: a suite page loads an iframe that fetches the catalogues and
    # both data files concurrently, and a single-threaded server deadlocks on the first one.
    server = http.server.ThreadingHTTPServer(("127.0.0.1", port), handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    return server


def write_fixture():
    source = (REPO / "index.html").read_text(encoding="utf-8")
    if "</head>" not in source:
        sys.exit("index.html has no </head> — cannot build the data-error fixture.")
    FIXTURE.write_text(source.replace("</head>", FIXTURE_SHIM, 1), encoding="utf-8")


def run_suite(chrome, port, page, budget_s):
    """Load one suite and return its <pre id="out"> text."""
    with tempfile.TemporaryDirectory() as profile:
        proc = subprocess.run(
            [
                chrome,
                "--headless=new",
                "--disable-gpu",
                "--no-sandbox",
                "--disable-dev-shm-usage",
                f"--user-data-dir={profile}",
                f"--virtual-time-budget={budget_s * 1000}",
                "--dump-dom",
                f"http://127.0.0.1:{port}/_tests/{page}",
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=budget_s * 3 + 60,
        )

    match = re.search(r'<pre id="out">(.*?)</pre>', proc.stdout, re.S)
    if not match:
        return None
    return html.unescape(match.group(1)).strip()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("suites", nargs="*", help="suite names to run (default: all)")
    parser.add_argument("--list", action="store_true", help="list suite names and exit")
    parser.add_argument("--keep", action="store_true", help="keep the generated fixture")
    parser.add_argument("--quiet", action="store_true", help="only print failures")
    args = parser.parse_args()

    if args.list:
        for name, page, _ in SUITES:
            print(f"{name:14} _tests/{page}")
        return 0

    selected = SUITES
    if args.suites:
        known = {name for name, _, _ in SUITES}
        unknown = [s for s in args.suites if s not in known]
        if unknown:
            sys.exit(f"Unknown suite(s): {', '.join(unknown)}. Try --list.")
        selected = [s for s in SUITES if s[0] in args.suites]

    chrome = find_chrome()
    port = free_port()
    server = serve(port)
    write_fixture()

    total_assertions = 0
    failed_suites = []

    try:
        for name, page, budget in selected:
            output = run_suite(chrome, port, page, budget)

            if output is None:
                print(f"FAIL  {name:14} produced no output (did the page throw before rendering?)")
                failed_suites.append(name)
                continue

            fail_lines = [ln for ln in output.splitlines() if ln.startswith("FAIL")]
            passed = re.search(r"ALL PASS \((\d+)\)", output)

            if passed and not fail_lines:
                count = int(passed.group(1))
                total_assertions += count
                if not args.quiet:
                    print(f"ok    {name:14} {count} assertions")
                continue

            failed_suites.append(name)
            total_assertions += len([ln for ln in output.splitlines() if ln.startswith(("PASS", "FAIL"))])
            print(f"FAIL  {name:14} {len(fail_lines)} failing")
            for line in fail_lines:
                print(f"        {line}")
            if not fail_lines:
                # No verdict marker and no FAIL lines: it hung part-way through.
                print(f"        no verdict — last line was: {output.splitlines()[-1][:120]!r}")
    finally:
        server.shutdown()
        if not args.keep and FIXTURE.exists():
            FIXTURE.unlink()

    print()
    if failed_suites:
        print(f"{len(failed_suites)} suite(s) failed: {', '.join(failed_suites)}")
        return 1
    print(f"All {len(selected)} suites passed ({total_assertions} assertions).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
